// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kDebugMode, kIsWeb;
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        // Removed the if(!kIsWeb) block as it's not valid syntax here.
        apiKey: kIsWeb && kDebugMode
            ? dotenv.env['API_KEY']!
            : const String.fromEnvironment('API_KEY', defaultValue: ''),
        authDomain: kIsWeb && kDebugMode
            ? dotenv.env['AUTH_DOMAIN']!
            : const String.fromEnvironment('AUTH_DOMAIN', defaultValue: ''),
        projectId: kIsWeb && kDebugMode
            ? dotenv.env['PROJECT_ID']!
            : const String.fromEnvironment('PROJECT_ID', defaultValue: ''),
        storageBucket: kIsWeb && kDebugMode
            ? dotenv.env['STORAGE_BUCKET']!
            : const String.fromEnvironment('STORAGE_BUCKET', defaultValue: ''),
        messagingSenderId: kIsWeb && kDebugMode
            ? dotenv.env['MESSAGING_SENDER_ID']!
            : const String.fromEnvironment('MESSAGING_SENDER_ID',
                defaultValue: ''),
        appId: kIsWeb && kDebugMode
            ? dotenv.env['APP_ID']!
            : const String.fromEnvironment('APP_ID', defaultValue: ''),
        measurementId: kIsWeb && kDebugMode
            ? dotenv.env['MEASUREMENT_ID']!
            : const String.fromEnvironment('MEASUREMENT_ID', defaultValue: ''),
      );
}
